# Generated by Django 5.1.4 on 2024-12-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_one.place')),
            ],
            bases=('app_one.place',),
        ),
    ]
