# Generated by Django 5.1.4 on 2024-12-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_otherperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='oneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='anotherModel',
            fields=[
                ('onemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='first_app.onemodel')),
                ('anothername', models.CharField(max_length=120)),
            ],
            bases=('first_app.onemodel',),
        ),
    ]
