# Generated by Django 5.1.4 on 2024-12-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_range'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Range',
        ),
    ]
