# Generated by Django 5.1.4 on 2025-01-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=' none ', max_length=120),
            preserve_default=False,
        ),
    ]
