# Generated by Django 5.1.4 on 2024-12-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_group_person_membership_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
            ],
        ),
    ]
