# Generated by Django 5.1.4 on 2024-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(default='2020-10-10'),
        ),
    ]
